name: Build & Deploy OSINT Report

on:
  schedule:
    - cron: "17 2 * * *"
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true

      - name: Build report (HTML + CSV)
        run: |
          mkdir -p docs
          python3 scripts/osint_harvester_max.py \
            -i "./examples/*.json" \
            -o "./docs/index.html" \
            --title "OSINT theHarvester Report (GitHub Pages)" \
            --export-csv

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
