name: Build & Deploy report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps (если у тебя есть requirements.txt — оставь, иначе пропустится)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build report (examples -> docs/index.html)
        run: |
          mkdir -p docs
          python json2html_ultra_max.py \
            -i "./examples/*.json" \
            -o ./docs/index.html \
            --title "OSINT theHarvester Report: ${{ github.repository }}"

      - name: Add .nojekyll (чтобы работали пути/подпапки)
        run: |
          touch docs/.nojekyll

      - name: Commit docs to main
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs || true
          git commit -m "Update report [skip ci]" || echo "No changes"
          git push

  # опционально: можно собирать через Pages API, но у нас уже лежит файл в docs.

