name: Release OSINT Report

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps (optional)
        if: hashFiles('requirements.txt') != ''
        run: pip install -r requirements.txt

      - name: Build export bundle
        run: |
          mkdir -p dist
          python3 json2html_ultra_max.py \
            -i "examples/*.json" \
            -o dist/report.html \
            --title "OSINT theHarvester Report (release $GITHUB_REF_NAME)" \
            --export-csv
          # сложим всё удобным набором
          cp -v examples/*.json dist/ 2>/dev/null || true
          # (если в твоём скрипте есть экспорт в .xlsx — тоже скопируется)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
          generate_release_notes: true

