name: Run OSINT Search (person/org)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Search mode: person or org"
        required: true
        default: "person"
        type: choice
        options: [person, org]
      query:
        description: "Person full name (for person) OR company/org name (for org)"
        required: true
        type: string
      domain:
        description: "Primary domain (for org mode, optional)"
        required: false
        type: string
      country:
        description: "Country/region code (optional, e.g. US, RU, DE)"
        required: false
        type: string
      lang:
        description: "Preferred content language (optional, e.g. en, ru)"
        required: false
        type: string

permissions:
  contents: write     # чтобы коммитить результаты в репо
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  run-search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true

      - name: Ensure dirs
        run: |
          mkdir -p reports docs

      - name: Run person/org search
        env:
          COUNTRY: ${{ github.event.inputs.country }}
          LANG:    ${{ github.event.inputs.lang }}
        run: |
          ts="$(date -u +'%Y%m%d-%H%M%S')"
          if [ "${{ github.event.inputs.mode }}" = "person" ]; then
            python3 scripts/person_search.py \
              --name "${{ github.event.inputs.query }}" \
              ${COUNTRY:+--country "$COUNTRY"} \
              ${LANG:+--lang "$LANG"} \
              --out "reports/person_${ts}.json"
          else
            python3 scripts/org_search.py \
              --org  "${{ github.event.inputs.query }}" \
              ${COUNTRY:+--country "$COUNTRY"} \
              ${LANG:+--lang "$LANG"} \
              ${ { github.event.inputs.domain } && echo "--domain \"${{ github.event.inputs.domain }}\"" ; } \
              --out "reports/org_${ts}.json"
          fi

      - name: Build HTML (merge examples + new reports)
        run: |
          python3 scripts/osint_harvester_max.py \
            -i "examples/*.json" "reports/*.json" \
            -o "./docs/index.html" \
            --title "OSINT theHarvester Report (GitHub Pages)" \
            --export-csv

      - name: Commit JSON and CSV (history)
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add reports/ docs/*.csv || true
          git commit -m "chore: add ${{ github.event.inputs.mode }} search '${{ github.event.inputs.query }}'" || echo "Nothing to commit"
          git push || true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: run-search
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
