name: Manual OSINT Search (People / Org)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "people|org"
        required: true
        default: "people"
      query:
        description: "For mode=people: name/email/username; for mode=org: domain"
        required: true
      title:
        description: "Report title"
        required: false
        default: "OSINT custom run"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  search-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true

      - name: Run OSINT search
        run: |
          mkdir -p reports docs
          if [ "${{ github.event.inputs.mode }}" = "people" ]; then
            python3 scripts/person_search.py --query "${{ github.event.inputs.query }}" --out reports/run.json
          else
            python3 scripts/org_search.py --domain "${{ github.event.inputs.query }}" --out reports/run.json
          fi

      - name: Build report
        run: |
          python3 scripts/osint_harvester_max.py \
            -i "reports/run.json" \
            -o "docs/index.html" \
            --title "${{ github.event.inputs.title }}" \
            --export-csv

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    needs: search-and-build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
